enum RouteNames {
  LOGIN = 'LOGIN',
  DASHBOARD = 'DASHBOARD',
  CLIENT_LIST = 'CLIENT_LIST',
  CLIENT_NEW = 'CLIENT_NEW',
  CLIENT_EDIT = 'CLIENT_EDIT',

  SERVICE_LIST = 'SERVICE_LIST',
  SERVICE_NEW = 'SERVICE_NEW',
  SERVICE_EDIT = 'SERVICE_EDIT',

  CONTRACT_LIST = 'CONTRACT_LIST',
  CONTRACT_NEW = 'CONTRACT_NEW',
  CONTRACT_EDIT = 'CONTRACT_EDIT',
  INVOICE_LIST = 'INVOICE_LIST',
  INVOICE_NEW = 'INVOICE_NEW',
  INVOICE_EDIT = 'INVOICE_EDIT',

  USER_LIST = 'USER_LIST',
  USER_NEW = 'USER_NEW',
  USER_EDIT = 'USER_EDIT',

  SERVICE_TYPE_LIST = 'SERVICE_TYPE_LIST',
  SERVICE_TYPE_NEW = 'SERVICE_TYPE_NEW',
  SERVICE_TYPE_EDIT = 'SERVICE_TYPE_EDIT',

  SERVICE_REQUEST_LIST = 'SERVICE_REQUEST_LIST',
  SERVICE_REQUEST_NEW = 'SERVICE_REQUEST_NEW',
  SERVICE_REQUEST_EDIT = 'SERVICE_REQUEST_EDIT',

  COMMERCIAL_OFFER_LIST = 'COMMERCIAL_OFFER_LIST',
  COMMERCIAL_OFFER_NEW = 'COMMERCIAL_OFFER_NEW',
  COMMERCIAL_OFFER_EDIT = 'COMMERCIAL_OFFER_EDIT',
}

export default RouteNames;
